#!/usr/bin/env bash
# Generate human-readable asset metadata from the authoritative shell manifest.
# shellcheck disable=SC2016
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/pinned-assets.sh
. "$SCRIPT_DIR/pinned-assets.sh"
printf '# Downloaded assets\n\nGenerated by `scripts/asset-manifest.sh`; edit `scripts/pinned-assets.sh`.\n\n'
printf '| Asset | Version | File | SHA256 |\n|---|---|---|---|\n'
while IFS= read -r key; do
  [[ "$key" != tokei-cargo ]] || continue
  printf '| [%s](%s) | `%s` | `%s` | `%s` |\n' "$key" "$(pinned_asset_field "$key" url)" "$(pinned_asset_field "$key" version)" "$(pinned_asset_field "$key" file)" "$(pinned_asset_field "$key" sha256)"
done < <(sed -n 's/^    \([^ :]*\):version).*/\1/p' "$SCRIPT_DIR/pinned-assets.sh")
