# Legacy matrix profile. Operator is the recommended default.
background = 061009
foreground = c4ffd4
cursor-color = b4ff59
cursor-style = block
selection-background = 234052
selection-foreground = c4ffd4
background-opacity = 0.94
background-blur = 20
window-padding-x = 16
window-padding-y = 14
palette = 0=#061009
palette = 1=#ff667a
palette = 2=#b4ff59
palette = 3=#ffda73
palette = 4=#43ff75
palette = 5=#22bba9
palette = 6=#43ff75
palette = 7=#c4ffd4
palette = 8=#547083
palette = 9=#ff8da2
palette = 10=#b4ff59
palette = 11=#ffe7a0
palette = 12=#43ff75
palette = 13=#22bba9
palette = 14=#a4f4ff
palette = 15=#ffffff
